### ISSUE TITLE
6.0.3 Support

### ISSUE THREAD

**Issue by nleach7** [PSPDFKit/Xamarin-Android#14]
Any word on when PSPDFKit 6.0.3 support will be coming?

I'm evaluating this for use at my company and only have access to 6.0.3 with my trial license. 6.0.3 is incompatible with this project.

**Comment by ChrisixFlash** [comment]
Hi there, a new version for PSPDFKit for Xamarin Android should be available soon. I can't promise anything yet as it still has to go through QA as well but it should be ready in the next couple of weeks.

**Comment by simoarpe** [comment]
I'm glad to tell you that Xamarin bindings have been updated to v6.0.3 https://github.com/PSPDFKit/Xamarin-Android/commit/dc4ec57a1e6751e4e8e3eb732ded2d24a54f15c5
I'm closing this issue.
