### ISSUE TITLE
Errors while executing "make dll"

### ISSUE THREAD

**Issue by itunik** [PSPDFKit/Xamarin-Android#4]
Hi,
I'm trying to fit PSPDFKit into Xamarin application. Followed the instructions, but "make dll" command fails with errors on latest code base.

`/Users/<username>/Projects/PSPDFKitXamarin-Android/PSPDFKit.Android/PSPDFKit.Android.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.Targets (CoreCompile target) ->

	obj/Release/generated/src/PSPDFKit.Document.Editor.Page.NewPageDialog.cs(401,20): error CS0102: The type `PSPDFKit.Document.Editor.Page.NewPageDialog.ColorsAdapter' already contains a definition for `cb_onCreateViewHolder_Landroid_view_ViewGroup_I'
	obj/Release/generated/src/PSPDFKit.Document.Editor.Page.NewPageDialog.cs(419,18): error CS0102: The type `PSPDFKit.Document.Editor.Page.NewPageDialog.ColorsAdapter' already contains a definition for `id_onCreateViewHolder_Landroid_view_ViewGroup_I`

Could you please help with resolving issues?

**Comment by steipete** [comment]
Hi there! Can you post what versions of Xamarin/Mono/Android Studio/SDK you have all installed?
Also verify that you're not using Xamarin.Forms as there's still an incompatibility with them (they need to first migrate to the newer support library to allow both)

**Comment by itunik** [comment]
Hi! Is it in Library folder?
I'm using Visual Studio for Mac currently. I'm stuck at step 2 from instructions. There is no yet reference to Xamarin.Forms.

**Comment by steipete** [comment]
Please try with latest beta of Xamarin Studio. Visual Studio still has various issues.

**Comment by itunik** [comment]
Verified with Xamarin Studio, works. Thanks!

**Comment by steipete** [comment]
Thanks for getting back here. Compatibility with Visual Studio is a mid-term goal and we're working with Xamarin to make this happen - I'm confident that we'll get there this year.
