### ISSUE TITLE
Creating binding file for v3.2.1 errors out with 2 errors

### ISSUE THREAD

**Issue by wyattblake** [PSPDFKit/Xamarin-Android#6]
Error CS0535: 'EpicenterTranslateClipReveal.StateEvaluator' does not implement interface member 'ITypeEvaluator.Evaluate(float, Object, Object)' (CS0535) (PSPDFKit.Android)

Error CS0534: 'EpicenterTranslateClipReveal.StateProperty' does not implement inherited abstract member 'Property.Get(Object)' (CS0534) (PSPDFKit.Android)

**Comment by dalexsoto** [comment]
Hello this should be fixed now in latest master!
